### ISSUE TITLE
BeaconOutput undefined

### ISSUE THREAD

**Issue by social323** [kyxiaxiang/Beacon_Source#4]
How to implement BeaconOutput

**Comment by kyxiaxiang** [comment]
Thank you very much for asking this question. This code is incomplete and experimental. Regarding the implementation of BeaconOutput, it may be confused with the BOF method in this Beacon code. 

I will correct it later when I get back to it. More Beacon APIs are not yet complete. Some callback and BOF outputs are confused here. If it is just Bof's BeaconOutPut, you can refer to 

https://github.com/TheWover/community-modules/blob/3cb335f86677c363aa0f511716c7dbb8d261add4/invoke-bof/windows/src/beacon_compatibility.c#L238

At the same time, you can refer to wbglil’s rebeacon.

There are still many flaws in this project. If I have time, I will continue to adjust it bit by bit.
